### PR TITLE
add .open() to load initial state

### PR DESCRIPTION
**Pull request by juliangruber**
Adding an `.open()` method which you use to read the initial state. Otherwise, the next write to the db will overwrite what was initially there.

### CODE REVIEW

**Comment by juliangruber** [comment]
so `state` is never ever read from the file, which means when you write one key value pair, it will overwrite the file with just that key value pair.

**Comment by juliangruber** [comment]
My suggestion is to provide an `.init` method that will fill state initially

**Review by yoshuawuyts — APPROVED** [review]
LGTM

**Comment by joehand** [comment]
1.4.0

**Pull request merged**
